name: grievance_system
description: A comprehensive online grievance redressal system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:

  flutter:
    sdk: flutter
  dartz: ^0.10.1  
  get_it: ^8.2.0    
  
  
  flutter_local_notifications: ^19.4.2
  

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Backend Services
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_messaging: ^16.0.2
  supabase_flutter: ^2.10.1
  
  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  
  # UI & Navigation
  go_router: ^16.2.2
  cached_network_image: ^3.2.3
  image_picker: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  
  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Utilities
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  
  # AI Integration
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  retrofit_generator: ^8.2.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
  
  # Testing
  mocktail: ^1.0.0
  bloc_test: ^10.0.0
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
