// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPUvBYhvGMdcBj9sj4yGFobqtlAjGtGwk',
    appId: '1:387064087030:web:3b7e422fc1d4abdca4c7d7',
    messagingSenderId: '387064087030',
    projectId: 'complaintmanagement-2c673',
    authDomain: 'complaintmanagement-2c673.firebaseapp.com',
    storageBucket: 'complaintmanagement-2c673.firebasestorage.app',
    measurementId: 'G-9EEXPQY586',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSSJTCFPJnDtEGo7IyLgS7w_Yli9D18w',
    appId: '1:387064087030:android:5363a77e1887174da4c7d7',
    messagingSenderId: '387064087030',
    projectId: 'complaintmanagement-2c673',
    storageBucket: 'complaintmanagement-2c673.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4PaG7zrnXgFY0ymMpHeFURbfhJmzXb7E',
    appId: '1:387064087030:ios:c9fcbc8a34db0a69a4c7d7',
    messagingSenderId: '387064087030',
    projectId: 'complaintmanagement-2c673',
    storageBucket: 'complaintmanagement-2c673.firebasestorage.app',
    iosBundleId: 'com.example.grivianceSystem1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4PaG7zrnXgFY0ymMpHeFURbfhJmzXb7E',
    appId: '1:387064087030:ios:c9fcbc8a34db0a69a4c7d7',
    messagingSenderId: '387064087030',
    projectId: 'complaintmanagement-2c673',
    storageBucket: 'complaintmanagement-2c673.firebasestorage.app',
    iosBundleId: 'com.example.grivianceSystem1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPUvBYhvGMdcBj9sj4yGFobqtlAjGtGwk',
    appId: '1:387064087030:web:e3a28c114f269778a4c7d7',
    messagingSenderId: '387064087030',
    projectId: 'complaintmanagement-2c673',
    authDomain: 'complaintmanagement-2c673.firebaseapp.com',
    storageBucket: 'complaintmanagement-2c673.firebasestorage.app',
    measurementId: 'G-TKN6SFYLP2',
  );
}
